# Generated by Django 2.0.3 on 2018-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
